### ISSUE TITLE
Double Sem PS-2 page not accounted for

### ISSUE THREAD

**Issue by genstack** [gaurabdg/PS2-Form-Filler#4]
Hey it would be great if you could make a version that works for double sem students too. I'll help with the sitemap:
the first page we get when we enter our credentials has two buttons: sem1 or sem2.
Pic attached.
It would be great if you could make a version that works with this sitemap as well.
Thanks!
![Screenshot from 2019-11-26 07-09-42](https://user-images.githubusercontent.com/58197095/69592392-c4321780-101b-11ea-8508-fe30cd285b11.png)

**Comment by gaurabdg** [comment]
I need to inspect the webpages, so I'll add the functionalities if you could share your credentials(PM in FB)
Closing the issue.
