### ISSUE TITLE
still downloads prev sem list

### ISSUE THREAD

**Issue by nitinvinayak** [gaurabdg/PS2-Form-Filler#5]
Please change the BatchIdFor to 10 & PSTypeFor to 2 on line 169 in the script file

And recreate the jar executable file for sem 1 stationlist

**Comment by gaurabdg** [comment]
Done, please redownload and let me know. I am hereby closing this issue as it has been resolved. Thanks for your feedback!

**Comment by nitinvinayak** [comment]
Thanks for fixing the issue
